/**
 * Per-pack content coverage report, written to docs/content-coverage.md.
 *   npx tsx scripts/content-coverage.ts
 */
import { writeFileSync } from "node:fs";
import { getAllScenarioPacks } from "@/data/scenarioPacks";
import { getPlayableIncidents } from "@/data/incidentQuality";

const packs = [...getAllScenarioPacks()].sort((a, b) => a.level - b.level);
const formatsSeen = new Set<string>();
const rows = packs.map((pack) => {
  const byFormat: Record<string, number> = {};
  let cascades = 0;
  let variants = 0;
  let logs = 0;
  for (const inc of pack.incidents) {
    const f = inc.format ?? "pick";
    formatsSeen.add(f);
    byFormat[f] = (byFormat[f] ?? 0) + 1;
    if (inc.isCascade) cascades++;
    variants += inc.variants?.length ?? 0;
    if (inc.logs && Object.keys(inc.logs).length > 0) logs++;
  }
  return { pack, byFormat, cascades, variants, logs, playable: getPlayableIncidents(pack).length };
});

const formats = [...formatsSeen].sort();
const lines = [
  "# Content coverage",
  "",
  "Generated by `npx tsx scripts/content-coverage.ts`. Do not edit by hand.",
  "",
  `| Lvl | Pack | Incidents | Playable | Cascades | Variants | With logs | ${formats.join(" | ")} |`,
  `| ---: | :--- | ---: | ---: | ---: | ---: | ---: | ${formats.map(() => "---:").join(" | ")} |`,
  ...rows.map(
    (r) =>
      `| ${r.pack.level} | ${r.pack.patternId} | ${r.pack.incidents.length} | ${r.playable} | ${r.cascades} | ${r.variants} | ${r.logs} | ${formats
        .map((f) => r.byFormat[f] ?? 0)
        .join(" | ")} |`
  ),
  "",
  `Totals: ${rows.reduce((n, r) => n + r.pack.incidents.length, 0)} incidents, ${rows.reduce((n, r) => n + r.logs, 0)} with authored logs.`,
  "",
  "Packs with no authored logs or a single format are the next content targets.",
  "",
];
writeFileSync("docs/content-coverage.md", lines.join("\n"), "utf8");
console.log(`wrote docs/content-coverage.md (${rows.length} packs)`);
